server:
  port: ${PORT:${SERVER_PORT:8080}}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - name: FilterCustom 
      routes:
        #- id: mscourse #identificador de la ruta
          - id: jsonplaceholder
          #uri: lb://ms-course #URL donde se hará el redirect segun el predicado definido
            uri: https://jsonplaceholder.typicode.com
          predicates: #Reglas de analisis de request
            - Path=/todos/** #path de url de request a considerar
       # - id: mssubscription
          - id: httpbin
        #  uri: lb://ms-subscription
            uri: https://httpbin.org
         predicates:
            - Path=/get/**              

info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka
  management:
    endpoint:
      gateway:
        enabled: true
    endpoints: 
      web:
        exposure:
          include: gateway
