server:
  port: ${PORT:${SERVER_PORT:0}}

idRandom: ${random.value}
denominaciones: "10,20,50,100,200,500"
cantidadMaxima: 100000
spring:
  application:
    name: ms-course
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
